#!/usr/bin/env python3
"""Acrescenta uma segunda camada de conhecimento específico às 116 aulas.

O script não cria tópicos. Ele exige que cada ID da matriz oficial tenha uma
entrada própria de aprofundamento e injeta esse conteúdo na aula já expandida.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
CONTEST_ID = "gcm-salvador-2026"
LESSONS_PATH = DATA / "lessons" / f"{CONTEST_ID}.json"
SYLLABUS_PATH = DATA / "syllabus" / f"{CONTEST_ID}.json"

K = {
# Língua Portuguesa
"interpretacao-argumentativa": [
"Tese é a ideia que o autor quer fazer o leitor aceitar; argumento é o caminho usado para sustentar essa ideia. Dado, exemplo, comparação, causa e consequência podem funcionar como argumentos.",
"Inferir não é inventar. Uma inferência válida nasce de pistas do texto; uma conclusão baseada apenas em conhecimento externo não é interpretação textual.",
"Observe modalizadores: 'pode' indica possibilidade; 'deve' pode indicar obrigação ou probabilidade; 'sempre' e 'nunca' tornam a afirmação absoluta e costumam alterar o alcance do texto.",
"Em textos argumentativos, identifique também contraponto e concessão: o autor pode reconhecer uma objeção e, mesmo assim, manter a tese principal."
],
"construcao-textual": [
"A construção do texto depende da ordem das ideias: apresentação do tema, desenvolvimento, exemplificação, explicação, contraponto e conclusão podem cumprir funções diferentes.",
"Referência anafórica retoma algo já mencionado; referência catafórica antecipa algo que será explicado depois. Pronomes e expressões equivalentes ajudam a manter o fio do texto.",
"Um parágrafo não é apenas um bloco visual: ele costuma desenvolver uma unidade de sentido. Mudança brusca de assunto pode prejudicar continuidade e coerência.",
"Conectores indicam relações como causa, consequência, oposição, concessão, condição, finalidade, explicação e conclusão."
],
"progressao-textual": [
"Progressão ocorre quando o texto retoma informação conhecida e acrescenta informação nova. Repetir palavras não é necessariamente erro se houver avanço de sentido.",
"Uma ideia pode progredir por detalhamento, exemplificação, causa, consequência, comparação, contraste ou conclusão.",
"Se cada frase apenas reformula a anterior sem acrescentar nada relevante, o texto pode ficar circular ou redundante.",
"Na prova, pergunte: 'o que esta frase acrescentou ao que já estava dito?'. Essa pergunta ajuda a reconhecer a função do trecho."
],
"coesao-coerencia-intertextualidade": [
"Coesão é visível na linguagem: pronomes, repetição controlada, sinônimos e conectores ligam partes do texto. Coerência é a compatibilidade global das ideias.",
"Um texto pode ser coeso e incoerente: conectores podem estar corretos mesmo quando as afirmações se contradizem.",
"Intertextualidade aparece por citação, alusão, paródia ou referência reconhecível a outro texto/discurso.",
"Na coesão referencial, confirme sempre qual termo é retomado; ambiguidade de referência pode mudar completamente a interpretação."
],
"reescritura": [
"Reescrever mantendo sentido exige preservar relações lógicas, tempo verbal, sujeito, negação, intensidade e grau de certeza.",
"Trocar voz ativa por passiva pode preservar o fato básico, mas altera foco e estrutura; confira se agente, paciente e tempo verbal foram mantidos.",
"Negação merece atenção especial: 'todos fizeram' não é equivalente a 'ninguém deixou de fazer' em qualquer reformulação sem análise lógica do contexto.",
"Conectores aparentemente próximos podem mudar a relação: 'porque' tende a introduzir causa/explicação; 'portanto' introduz conclusão."
],
"vocabulario": [
"Sinônimos são contextuais: duas palavras próximas no dicionário podem não ser substituíveis na frase concreta.",
"Polissemia é a existência de vários sentidos para uma mesma palavra. O contexto seleciona qual sentido está ativo.",
"Antônimos também dependem do contexto: o contrário de 'claro' muda conforme se fala de luminosidade, linguagem ou evidência.",
"Em prova, substitua mentalmente a palavra pela alternativa e releia a frase inteira; se o sentido ou registro mudar, a equivalência falhou."
],
"estrangeirismos": [
"Estrangeirismo é empréstimo lexical de outra língua. Alguns termos mantêm forma estrangeira; outros sofrem adaptação gráfica ou fonética.",
"A presença de estrangeirismo não torna o texto automaticamente inadequado. A análise depende de finalidade, público e contexto.",
"Em tecnologia, negócios e cultura, estrangeirismos são frequentes; a banca pode cobrar reconhecimento e adequação de uso.",
"Diferencie palavra estrangeira de erro ortográfico: origem externa e incorreção gráfica são fenômenos diferentes."
],
"classes-palavras": [
"As classes tradicionais incluem substantivo, adjetivo, artigo, numeral, pronome, verbo, advérbio, preposição, conjunção e interjeição.",
"A classificação depende do uso: 'rápido' pode funcionar como adjetivo em 'carro rápido' e ter comportamento adverbial em construções específicas.",
"Conjunções e preposições são especialmente importantes porque ligam termos e orações e ajudam a construir relações de sentido.",
"Antes de classificar uma palavra, observe o que ela modifica, substitui, determina ou conecta na frase."
],
"sintaxe-pontuacao": [
"Comece pela estrutura: identifique verbo, sujeito, complementos e termos deslocados. A pontuação acompanha a sintaxe, não apenas a pausa da fala.",
"A vírgula não deve separar sujeito e verbo nem verbo e complemento direto sem motivo sintático específico.",
"Vírgulas podem marcar enumeração, vocativo, aposto, termos deslocados/intercalados e separar determinadas orações.",
"Mudar pontuação pode mudar sentido. Em provas de reescrita, confirme se a nova pontuação altera referência, explicação, restrição ou relação entre orações."
],
"variacao-linguistica": [
"Variação diatópica relaciona-se a região; diastrática, a grupos sociais; diafásica, à situação e grau de formalidade; diacrônica, à mudança ao longo do tempo.",
"Variação não é sinônimo de erro. Uma forma pode ser legítima em determinada variedade e inadequada em um documento formal.",
"Adequação comunicativa considera interlocutor, finalidade, meio, situação e registro esperado.",
"Em concurso, norma-padrão costuma ser exigida na escrita formal, mas a questão pode pedir reconhecimento de variedades e efeitos de sentido."
],
"denotacao-conotacao": [
"Denotação privilegia sentido literal e informativo; conotação explora sentido figurado, associação e efeito expressivo.",
"Metáfora e outras figuras podem produzir conotação, mas o ponto central da questão é verificar se a expressão deve ser entendida literalmente ou figuradamente.",
"Contexto decide: a mesma palavra pode estar denotativa em uma frase e conotativa em outra.",
"Em textos informativos, linguagem denotativa tende a predominar; em publicidade e literatura, recursos conotativos são frequentes, mas não exclusivos."
],
"nova-ortografia": [
"O Acordo Ortográfico alterou principalmente acentuação, hífen e o uso do trema. A forma atual deve ser memorizada por padrões e exemplos frequentes.",
"O trema deixou de ser usado em palavras portuguesas, permanecendo apenas em nomes próprios estrangeiros e derivados quando cabível.",
"Alguns ditongos abertos em palavras paroxítonas perderam acento, enquanto oxítonas continuam seguindo regras próprias; estude exemplos comparativos.",
"No hífen com prefixos, observe a letra final do prefixo e a inicial do segundo elemento; casos como 'autoescola' e 'micro-ondas' ilustram regras diferentes."
],

# RLM
"proposicoes": ["Proposição é frase declarativa com valor verdadeiro ou falso; perguntas, ordens e exclamações normalmente não são proposições.", "Conjunção só é verdadeira com duas parcelas verdadeiras; disjunção inclusiva é verdadeira se pelo menos uma for verdadeira; condicional só é falsa no caso V→F.", "Negação deve atingir toda a estrutura lógica. Identifique o conectivo principal antes de negar uma proposição composta.", "Tabela-verdade é ferramenta de conferência: com n proposições simples, existem 2^n combinações de valores."],
"equivalencias": ["Equivalência significa mesmo valor lógico em todas as combinações possíveis, não apenas 'frases parecidas'.", "P→Q equivale a ¬P∨Q e à contrapositiva ¬Q→¬P.", "Leis de De Morgan trocam 'e' por 'ou' e negam as parcelas ao negar a expressão inteira.", "Recíproca Q→P e inversa ¬P→¬Q não são automaticamente equivalentes à condicional original."],
"problemas-raciocinio": ["Transforme relações verbais em símbolos, tabela ou ordem. Isso reduz carga de memória e evita trocar posições.", "Use primeiro pistas absolutas, depois relações relativas e, por fim, elimine cenários incompatíveis.", "Relações de ordem podem ser transitivas: se A vem antes de B e B antes de C, então A vem antes de C.", "Não conclua além das pistas: em lógica, uma possibilidade não é necessariamente uma conclusão obrigatória."],
"diagramas-graficos": ["Leia título, eixos, legenda, escala e unidade antes de comparar valores.", "Variação absoluta é diferença simples; variação percentual usa o valor inicial como base.", "Gráficos podem usar escalas truncadas e produzir impressão visual enganosa; confirme sempre os números.", "Tabela organiza valores discretos; gráfico ajuda a visualizar tendência, proporção e comparação, mas ambos exigem leitura da unidade."],
"conjuntos": ["União reúne elementos de A ou B; interseção reúne elementos comuns; diferença A−B mantém os elementos de A que não pertencem a B.", "Em dois conjuntos: |A∪B|=|A|+|B|−|A∩B|.", "No diagrama de Venn, preencha primeiro interseções e depois regiões exclusivas.", "Conjunto vazio não possui elementos; subconjunto é conjunto cujos elementos pertencem a outro conjunto."],
"numeros-operacoes": ["Naturais, inteiros, racionais e reais formam uma cadeia de inclusão útil para classificar números.", "Frações, decimais e porcentagens podem representar a mesma quantidade: 3/4=0,75=75%.", "Respeite prioridade: parênteses, potências, multiplicação/divisão e depois adição/subtração.", "Com números negativos, interprete sinal e operação separadamente para evitar erros de troca de sinal."],
"reta-numerica": ["Valores aumentam para a direita; entre negativos, o número mais próximo de zero é maior.", "Módulo |x| mede distância até zero e nunca é negativo.", "Distância entre a e b é |a−b|.", "Intervalos podem ser representados na reta; extremos abertos ou fechados indicam exclusão ou inclusão quando esse formalismo for usado."],
"unidades-medida": ["1 km=1.000 m; 1 m=100 cm; 1 kg=1.000 g; 1 h=60 min; 1 min=60 s.", "Antes de calcular, coloque todas as grandezas na mesma unidade.", "Conversão linear usa o fator diretamente; área usa o fator ao quadrado e volume ao cubo.", "Resultado sem unidade pode estar incompleto quando o problema pede medida física."],
"plano-cartesiano": ["Ponto é (x,y): x controla posição horizontal e y posição vertical.", "Quadrantes: I (+,+), II (−,+), III (−,−), IV (+,−).", "Se x=0, o ponto está no eixo y; se y=0, está no eixo x; (0,0) é a origem.", "Trocar a ordem das coordenadas geralmente produz outro ponto."],
"algebra": ["Equação traduz uma condição em igualdade. Faça a mesma operação nos dois membros para preservar a igualdade.", "Sistema linear exige que o mesmo par de valores satisfaça todas as equações.", "Problemas de 1º grau começam pela escolha da incógnita e tradução das relações do texto.", "Depois de resolver, substitua o resultado na equação original para conferir."],
"porcentagem-proporcao": ["p%=p/100. Para calcular p% de V, use V·p/100.", "Aumento e desconto incidem sobre uma base; percentuais sucessivos normalmente não podem ser simplesmente somados.", "Na proporcionalidade direta, as grandezas variam no mesmo sentido mantendo razão constante; na inversa, uma sobe enquanto a outra cai mantendo produto constante no modelo ideal.", "Regra de três é consequência de proporcionalidade, não uma fórmula universal: primeiro determine se a relação é realmente proporcional."],
"sequencias-pa-pg": ["PA tem diferença constante r; termo geral a_n=a_1+(n−1)r.", "PG tem razão multiplicativa constante q; termo geral a_n=a_1·q^(n−1).", "Nem toda sequência é PA ou PG. Procure padrão antes de aplicar fórmula.", "Questões podem apresentar padrão alternado, quadrados, crescimento por diferenças ou recorrência; teste mais de uma passagem entre termos."],
"juros": ["Juros simples incidem sobre o capital inicial: J=C·i·t e M=C+J.", "Juros compostos acumulam: M=C(1+i)^t.", "Taxa e tempo precisam usar a mesma unidade: mês com mês, ano com ano.", "Em compostos, 10% + 10% em dois períodos produz fator 1,1², não simplesmente 20% sobre o valor inicial."],
"geometria-basica": ["Perímetro mede contorno; área mede superfície. Unidades são lineares para perímetro e quadradas para área.", "Retângulo A=b·h; quadrado A=l²; triângulo A=b·h/2.", "Circunferência tem comprimento 2πr; círculo tem área πr².", "Soma dos ângulos internos de um triângulo plano é 180°."],
"semelhanca-triangulo": ["Triângulos semelhantes têm ângulos correspondentes iguais e lados correspondentes proporcionais.", "No triângulo retângulo, h²=a²+b² pelo Teorema de Pitágoras.", "Identifique corretamente a hipotenusa: é o lado oposto ao ângulo reto e o maior lado.", "Em proporção de semelhança, mantenha a correspondência entre lados; inverter apenas uma razão gera erro."],
"medidas-area-volume": ["Comprimento é 1D, área 2D e volume 3D; isso determina como os fatores de conversão são elevados.", "1 m²=10.000 cm² e 1 m³=1.000.000 cm³.", "Paralelepípedo retângulo: V=comprimento·largura·altura.", "Antes de somar áreas ou volumes, confirme que as unidades são compatíveis."],
"contagem-probabilidade": ["Princípio multiplicativo: escolhas sucessivas independentes são contadas multiplicando as quantidades de opções.", "Em modelo equiprovável, P(A)=casos favoráveis/casos possíveis.", "Probabilidade varia de 0 a 1 (ou 0% a 100%).", "Defina corretamente o espaço amostral; contar casos errados produz uma fração aparentemente correta com base incorreta."],

# Informática
"arquivos-digitais": ["Extensão ajuda a indicar formato, mas não garante conteúdo real do arquivo. Exemplos comuns: .docx, .xlsx, .pdf, .jpg, .png, .mp3, .mp4.", "Formato define como dados são estruturados e quais programas conseguem interpretá-los.", "Compactação pode reduzir tamanho; formatos podem ser com ou sem perdas, especialmente em imagem, áudio e vídeo.", "Renomear apenas a extensão não converte corretamente um arquivo para outro formato."],
"pdf": ["PDF busca preservar layout entre dispositivos e é muito usado para distribuição e impressão.", "Um PDF pode conter texto pesquisável, imagens, formulários, links e restrições de edição; não é necessariamente apenas uma imagem.", "Converter para PDF não significa que o conteúdo se torna imutável ou seguro automaticamente.", "Na prova, diferencie visualizar, editar, proteger e converter um documento."],
"windows": ["Pastas organizam arquivos e subpastas; caminho identifica localização no sistema de arquivos.", "Copiar preserva o original; mover altera localização; excluir envia normalmente para a Lixeira antes da remoção definitiva, conforme contexto.", "Busca do Windows localiza arquivos, aplicativos e recursos; ajuda e Painel de Controle/configurações têm finalidades distintas.", "Atalhos apontam para recursos e não são o próprio arquivo de destino."],
"editores-texto": ["Formatação de caractere envolve fonte, tamanho e destaque; formatação de parágrafo envolve alinhamento, recuo e espaçamento.", "Cabeçalho e rodapé podem repetir informações em páginas; quebra de página controla paginação.", "Tabelas organizam dados dentro do documento e não são equivalentes a planilhas de cálculo.", "Corretor ortográfico auxilia revisão, mas não garante correção semântica ou gramatical completa."],
"localizar-substituir": ["Localizar procura ocorrências; substituir troca ocorrências segundo critérios definidos.", "Substituir tudo pode alterar trechos indesejados se o termo for ambíguo; revise o critério.", "Ferramentas avançadas podem considerar maiúsculas/minúsculas, palavras inteiras e formatação.", "Localização e substituição economizam trabalho repetitivo, mas não interpretam contexto como uma revisão humana."],
"word-arquivos": ["Salvar grava alterações; Salvar como cria nova versão/nome/local/formato conforme escolha.", "Controle de alterações registra edições para revisão e aceitação/rejeição posterior.", "Proteção por senha pode restringir abertura ou edição conforme configuração; não substitui política adequada de segurança.", "Macros automatizam tarefas e podem conter código, razão pela qual arquivos com macros exigem atenção de segurança."],
"excel": ["Células são identificadas por coluna e linha, como A1. Fórmulas normalmente começam com '='.", "Referências relativas mudam ao copiar fórmulas; referências absolutas usam cifrões, como $A$1.", "Filtro exibe registros que atendem critérios; ordenação muda a ordem dos registros; são operações diferentes.", "Funções e fórmulas calculam valores; formatação muda aparência e não necessariamente o valor armazenado."],
"internet-seguranca": ["URL/endereço identifica recurso na rede; navegador interpreta e exibe conteúdos e aplicações web.", "Upload envia dados ao serviço remoto; download recebe dados para o dispositivo.", "Phishing tenta induzir o usuário a entregar dados ou executar ações; conferir origem, domínio e contexto é parte da navegação segura.", "Senha forte, autenticação adicional, criptografia e atualização reduzem riscos diferentes; nenhum mecanismo isolado resolve toda a segurança."],

# Constitucional e Civil
"const-conceito-principios": ["Constituição organiza o Estado, distribui poderes e protege direitos fundamentais; normas inferiores devem respeitá-la.", "Classificações constitucionais podem considerar origem, forma, extensão e estabilidade; o importante é reconhecer o critério usado pela questão.", "Princípios fundamentais orientam interpretação do sistema constitucional e não funcionam como simples slogans.", "Em prova, diferencie princípio, regra, objetivo fundamental e fundamento da República conforme a redação constitucional."],
"const-direitos": ["Direitos individuais e coletivos, direitos sociais, nacionalidade, direitos políticos e partidos integram o bloco de direitos fundamentais cobrado.", "Direitos fundamentais não são automaticamente absolutos; conflitos exigem interpretação constitucional e respeito a limites legítimos.", "Nacionalidade trata do vínculo jurídico-político com o Estado; cidadania relaciona-se ao exercício de direitos políticos e participação pública.", "Em direitos políticos, diferencie capacidade eleitoral ativa (votar) e passiva (ser votado), observados requisitos legais."],
"const-organizacao": ["A Federação brasileira distribui competências entre União, Estados, Distrito Federal e Municípios.", "Autonomia federativa envolve capacidade de auto-organização, autogoverno, autoadministração e competências próprias dentro da Constituição.", "Município não é subordinado administrativamente ao Estado; cada ente exerce competências constitucionais próprias.", "Questões costumam cobrar quem pode legislar, executar ou organizar determinada matéria; identifique primeiro o ente competente."],
"const-administracao": ["Administração Pública constitucional deve observar legalidade, impessoalidade, moralidade, publicidade e eficiência.", "Cargo, emprego e função pública não são sinônimos e possuem regimes jurídicos distintos.", "Ingresso em cargo ou emprego público depende, como regra, de concurso, ressalvadas hipóteses constitucionais.", "Responsabilidade, acumulação e direitos dos servidores devem ser estudados diretamente na redação constitucional vigente."],
"const-judiciario": ["Poder Judiciário possui órgãos e competências distribuídos constitucionalmente; identificar o órgão correto é essencial.", "Competência define qual órgão pode processar, julgar ou administrar determinada matéria.", "Garantias da magistratura e organização dos tribunais buscam preservar independência e funcionamento do Judiciário.", "Não confunda funções jurisdicionais dos tribunais com funções administrativas de seus órgãos de controle."],
"const-cnj": ["CNJ exerce controle administrativo, financeiro e disciplinar do Judiciário dentro das competências constitucionais.", "CNJ não substitui tribunais como instância recursal para rever decisões judiciais apenas por discordância do mérito.", "Composição e competências devem ser memorizadas pela redação constitucional vigente.", "Em prova, diferencie controle administrativo do CNJ de atividade jurisdicional dos órgãos judiciais."],
"const-funcoes-justica": ["Ministério Público, Advocacia Pública, Advocacia e Defensoria Pública exercem funções essenciais à Justiça em papéis distintos.", "Ministério Público atua na defesa da ordem jurídica e interesses previstos constitucionalmente; não é órgão do Judiciário.", "Defensoria Pública presta orientação e defesa jurídica aos necessitados nos termos constitucionais.", "A banca pode trocar atribuições entre instituições; identifique finalidade e destinatário de cada uma."],
"civil-lindb": ["LINDB disciplina aplicação, vigência, integração e interpretação das normas, funcionando como norma sobre normas.", "Analogia, costumes e princípios gerais ajudam a integrar lacunas nos limites jurídicos; não autorizam criar regra penal incriminadora.", "Aplicação da lei no tempo exige distinguir vigência, revogação e situações jurídicas já constituídas.", "Interpretação busca sentido da norma; integração resolve lacuna. Não confunda os dois processos."],
"civil-pessoas": ["Pessoa natural adquire personalidade civil conforme o Código Civil; capacidade trata da aptidão para exercer pessoalmente atos da vida civil.", "Pessoa jurídica possui personalidade distinta de seus integrantes, dentro dos limites legais.", "Domicílio é referência jurídica de localização da pessoa e pode seguir regras diferentes conforme situação.", "Emancipação antecipa capacidade civil plena em hipóteses legais, mas não elimina requisitos de idade previstos em outras áreas do direito."],
"civil-bens": ["Bens podem ser classificados por mobilidade, fungibilidade, divisibilidade, relação entre si e titularidade, entre outros critérios.", "Bens públicos pertencem às pessoas jurídicas de direito público e submetem-se a regime próprio.", "Bem principal existe sobre si; acessório pressupõe relação com outro bem, conforme classificação civil.", "A questão costuma descrever o objeto e pedir a classificação; identifique a característica usada no enunciado."],
"civil-fatos": ["Fato jurídico é acontecimento que produz efeitos jurídicos; negócio jurídico é manifestação de vontade destinada a produzir efeitos reconhecidos pelo direito.", "Ato ilícito envolve violação de dever jurídico e pode gerar responsabilidade civil.", "Prescrição atinge a pretensão; decadência relaciona-se à extinção de direito potestativo em hipóteses legais.", "Validade de negócio jurídico exige análise dos requisitos legais; nulidade e anulabilidade possuem regimes distintos."],
"civil-obrigacoes": ["Obrigação cria vínculo entre credor e devedor em torno de uma prestação de dar, fazer ou não fazer.", "Adimplemento é cumprimento; inadimplemento é descumprimento e pode gerar consequências como perdas e danos, juros e mora conforme o caso.", "Transmissão de obrigações pode envolver cessão de crédito e assunção de dívida, observados requisitos legais.", "Diferencie obrigação, responsabilidade e garantia: são conceitos relacionados, mas não idênticos."],
"civil-responsabilidade": ["Responsabilidade civil busca reparar dano decorrente de conduta juridicamente relevante conforme requisitos legais.", "Dano material e dano moral protegem interesses diferentes; ambos exigem análise do caso e do regime aplicável.", "Perda de uma chance trata da frustração séria e real de oportunidade, não de qualquer expectativa vaga.", "Desconsideração da personalidade jurídica é medida excepcional prevista em lei; não elimina a pessoa jurídica de forma geral."],
"civil-jurisprudencia": ["Jurisprudência é conjunto de decisões; súmula sintetiza entendimento consolidado em determinado tribunal.", "STF, STJ e TJBA possuem competências diferentes, por isso o peso e o objeto de seus precedentes variam.", "Leia a tese ou súmula dentro do assunto do edital e verifique se houve superação ou alteração legislativa.", "Não transforme um caso isolado em regra geral sem verificar o entendimento consolidado e o contexto."],

# Penal e Processo Penal
"penal-conceito-fontes": ["Direito Penal define infrações e sanções; sua intervenção é limitada por princípios como legalidade e anterioridade.", "Lei é fonte formal imediata para criação de crimes e penas; costumes não criam tipos penais incriminadores.", "Princípios orientam interpretação e limitam poder punitivo estatal.", "Diferencie fonte material (quem produz a norma) de fonte formal (forma de manifestação da norma)."],
"penal-lei": ["Legalidade impede crime ou pena sem lei anterior que os defina.", "Lei penal mais benéfica pode retroagir; lei mais gravosa não retroage para prejudicar, conforme regime constitucional e penal.", "Aplicação no espaço envolve regras de territorialidade e hipóteses legais de extraterritorialidade.", "Analogia não pode ser usada para criar crime ou agravar pena; integração benéfica possui tratamento distinto."],
"penal-teoria-crime": ["Fato típico envolve conduta, resultado quando exigido, nexo causal e tipicidade, conforme estrutura do delito.", "Dolo relaciona-se à vontade/assunção do risco nos termos legais; culpa envolve violação do dever de cuidado em modalidades previstas.", "Crime preterdoloso combina dolo no antecedente e culpa no resultado agravador quando a lei prevê.", "Nexo causal liga conduta ao resultado; sem esse vínculo, a imputação do resultado pode falhar."],
"penal-iter": ["Consumação ocorre quando todos os elementos do tipo estão realizados; tentativa pressupõe início de execução e não consumação por circunstâncias alheias à vontade do agente.", "Desistência voluntária ocorre quando o agente interrompe voluntariamente a execução; arrependimento eficaz ocorre quando impede o resultado após esgotar atos executórios.", "Arrependimento posterior tem requisitos próprios e ocorre após consumação de determinados crimes, com reparação/restituição dentro do prazo legal.", "Crime impossível decorre de ineficácia absoluta do meio ou impropriedade absoluta do objeto, conforme a lei."],
"penal-ilicitude": ["Ilicitude é contrariedade do fato típico ao ordenamento; legítima defesa, estado de necessidade, estrito cumprimento do dever legal e exercício regular de direito são excludentes previstas.", "Culpabilidade analisa possibilidade de reprovação pessoal, incluindo imputabilidade, potencial consciência da ilicitude e exigibilidade de conduta diversa na construção doutrinária usual.", "Excludente de ilicitude não é a mesma coisa que excludente de culpabilidade.", "Concurso de pessoas exige análise de vínculo entre participantes e contribuição para o fato, conforme regras do Código Penal."],
"penal-penas": ["Penas podem ser privativas de liberdade, restritivas de direitos e multa, conforme o sistema penal.", "Substituição de pena e regime de cumprimento dependem de requisitos legais; não são automáticos.", "Concurso material, formal e crime continuado possuem critérios diferentes para tratamento de múltiplos delitos.", "Medida de segurança possui fundamento e destinatários próprios e não se confunde com pena comum."],
"penal-sursis": ["Sursis suspende condicionalmente a execução da pena em hipóteses legais; não apaga a condenação automaticamente.", "Livramento condicional permite cumprimento do restante da pena em liberdade sob condições, após requisitos legais.", "Extinção da punibilidade encerra o poder estatal de punir em hipóteses previstas em lei.", "Não confunda prescrição, perdão, anistia, graça e indulto; possuem fundamentos e regimes diferentes."],
"penal-crimes-pessoa-patrimonio": ["Crimes contra a pessoa protegem bens como vida e integridade; crimes patrimoniais protegem relações patrimoniais; crimes sexuais protegem dignidade sexual.", "Furto e roubo não são sinônimos: violência ou grave ameaça é elemento decisivo para diferenciar figuras centrais.", "Nos crimes contra a pessoa, resultado, meio empregado e circunstâncias podem alterar a tipificação.", "Nos crimes sexuais, consentimento juridicamente válido e vulnerabilidade são elementos relevantes conforme o tipo legal."],
"penal-honra-fe-publica": ["Crimes contra a honra protegem honra objetiva ou subjetiva conforme a figura; calúnia, difamação e injúria possuem elementos distintos.", "Fé pública protege confiança social em documentos, sinais e declarações reconhecidas pelo ordenamento.", "Falsificação e uso de documento falso são condutas distintas e devem ser lidas no tipo correspondente.", "A banca costuma trocar o bem jurídico ou o verbo do tipo; leia a conduta descrita com precisão."],
"penal-administracao": ["Crimes contra a Administração Pública protegem regularidade, probidade e funcionamento da atividade estatal.", "Peculato, corrupção, concussão e prevaricação possuem sujeitos, verbos e finalidades diferentes.", "Crimes contra a Administração da Justiça atingem regular funcionamento da função jurisdicional e investigativa em hipóteses legais.", "Identifique se o tipo exige funcionário público, vantagem indevida, apropriação, solicitação, exigência ou finalidade específica."],
"penal-leis-especiais": ["O edital reúne várias leis penais especiais; estude cada uma separadamente antes de misturar conceitos.", "Organize por lei: bem jurídico, condutas principais, sujeitos, requisitos e efeitos. Isso reduz confusão entre diplomas.", "Nas leis alteradas recentemente, use a redação oficial vigente e marque dispositivos modificados.", "Evite decorar pena isolada antes de compreender o tipo e seus elementos; em prova, a descrição da conduta costuma vir antes do detalhe sancionatório."],
"proc-principios": ["Processo Penal constitucional é limitado por devido processo, contraditório, ampla defesa, presunção de inocência e juiz natural, entre outros princípios.", "Sistemas processuais descrevem distribuição de funções entre acusar, defender e julgar; o modelo constitucional exige separação de papéis.", "Princípios orientam interpretação das regras processuais, mas não autorizam ignorar texto legal expresso.", "Identifique se a questão trata de garantia do acusado, competência do juiz, iniciativa probatória ou atuação da acusação."],
"proc-aplicacao": ["Lei processual penal possui regra própria de aplicação no tempo: atos praticados sob lei anterior permanecem válidos, e a nova lei regula atos futuros, ressalvadas normas de natureza material.", "Aplicação no espaço segue regras do CPP e tratados/legislação especial conforme o caso.", "Norma processual e norma penal material podem coexistir no mesmo diploma; a natureza da regra influencia aplicação temporal.", "Disposições preliminares do CPP devem ser estudadas como base para todo o procedimento."],
"proc-inquerito": ["Inquérito policial é procedimento investigativo, em regra administrativo e inquisitivo, destinado a colher elementos sobre materialidade e autoria.", "Inquérito não é processo judicial e não resulta por si só em condenação.", "Autoridade policial realiza diligências nos limites legais; Ministério Público exerce funções próprias na persecução penal.", "Prazos, formas de instauração, indiciamento e arquivamento devem ser conferidos na legislação aplicável ao caso."],
"proc-processo": ["Processo é relação jurídica destinada à prestação jurisdicional; procedimento é a sequência de atos pela qual o processo se desenvolve.", "Pretensão punitiva é exercida por meio da ação penal conforme legitimidade e condições legais.", "Sujeitos processuais possuem funções distintas: juiz decide, acusação formula pretensão, defesa contrapõe e auxiliares exercem papéis próprios.", "Princípios informadores ajudam a compreender por que determinados atos exigem forma, contraditório e competência."],
"proc-acao": ["Ação penal pode ser pública ou privada conforme titularidade e regra legal.", "Na ação pública, Ministério Público exerce titularidade nos casos previstos; representação ou requisição podem ser condições em hipóteses específicas.", "Na ação privada, legitimidade e prazos seguem regime próprio.", "Diferencie condição para exercício da ação de prova do crime; são questões processuais diferentes."],
"proc-prova": ["Prova busca demonstrar fatos relevantes ao processo e está sujeita a regras de admissibilidade, produção e valoração.", "Prova ilícita possui tratamento constitucional e legal próprio; derivação de prova ilícita também exige análise das exceções legais.", "Interceptação telefônica depende de requisitos legais e autorização judicial; não se confunde com gravação realizada por um dos interlocutores.", "Cadeia de custódia e preservação da integridade do vestígio são importantes para confiabilidade da prova material."],
"proc-sujeitos": ["Juiz, Ministério Público, acusado, defensor, assistente e auxiliares possuem posições processuais distintas.", "Imparcialidade do juiz e defesa técnica são garantias estruturais do processo penal.", "Impedimento e suspeição tratam de situações que comprometem atuação de sujeitos processuais conforme a lei.", "A banca pode atribuir competência de um sujeito a outro; pergunte quem pode requerer, decidir, acusar ou defender."],
"proc-prisao": ["Prisão em flagrante, preventiva e temporária têm fundamentos e requisitos diferentes.", "Medidas cautelares diversas da prisão buscam adequar restrição à necessidade do caso quando previstas condições legais.", "Liberdade provisória não significa absolvição; trata da situação cautelar do investigado/acusado.", "Prisão cautelar não pode ser tratada como antecipação automática de pena."],
"proc-juizados": ["Juizados Especiais Criminais tratam infrações de menor potencial ofensivo conforme a Lei 9.099/1995 e possuem institutos despenalizadores próprios.", "Composição civil, transação penal e suspensão condicional do processo são institutos diferentes e possuem requisitos distintos.", "Lei 10.259/2001 disciplina Juizados Especiais Federais e interage com regras próprias da competência federal.", "Identifique competência, natureza da infração e instituto perguntado antes de aplicar regra do juizado."],
"proc-prazos": ["Prazo processual possui termo inicial, forma de contagem e consequências jurídicas próprias.", "Contagem no Processo Penal segue regras específicas; não transplante automaticamente critérios de outros ramos.", "Prazos podem variar conforme ato, sujeito e situação processual.", "Em questão objetiva, leia se o comando pergunta duração, início da contagem, natureza ou consequência do descumprimento."],
"proc-nulidades": ["Nulidade decorre de vício relevante no ato processual e exige análise do regime legal, finalidade da forma e eventual prejuízo.", "Nem todo defeito formal anula automaticamente o processo.", "Nulidades absolutas e relativas possuem tratamento distinto quanto a reconhecimento e preclusão.", "Princípio de que não há nulidade sem prejuízo é referência importante na análise processual, observadas exceções e jurisprudência."],
"proc-jurisprudencia": ["Jurisprudência dos tribunais superiores interpreta regras processuais e pode alterar compreensão prática de institutos.", "Leia precedentes dentro do tema do edital e verifique se são vinculantes, repetitivos, súmulas ou decisões não vinculantes.", "Mudança legislativa pode superar entendimento antigo; sempre relacione a data e a norma vigente.", "Não memorize frase de julgado sem compreender a situação fática e a questão jurídica decidida."],

# Administração e Políticas Públicas
"adm-introducao": ["Administração coordena recursos e pessoas para alcançar objetivos com eficácia e eficiência.", "Eficácia relaciona-se a atingir objetivo; eficiência, a relação entre resultados e recursos; efetividade costuma considerar impacto real.", "Evolução das teorias administrativas mostra mudança de foco: tarefas, estrutura, pessoas, comportamento, ambiente e contingência.", "Não trate uma teoria como totalmente substituta da anterior; muitas contribuições coexistem na prática."],
"adm-funcoes": ["PODC: planejar define objetivos/caminhos; organizar distribui recursos; dirigir mobiliza pessoas; controlar compara realizado com planejado.", "Controle não ocorre apenas no fim; pode ser preventivo, concomitante ou posterior.", "Planejamento sem controle não permite saber se a execução alcançou a meta.", "A banca pode descrever uma ação e pedir qual função administrativa está sendo exercida."],
"adm-teorias": ["Teoria clássica enfatiza estrutura e funções; relações humanas destaca fatores sociais; abordagem comportamental aprofunda comportamento e decisão; contingência rejeita solução única para todas as situações.", "Gestão por competências relaciona conhecimentos, habilidades e atitudes às necessidades organizacionais.", "Gestão de projetos organiza esforço temporário com objetivo, prazo, recursos e entregas definidos.", "Diferencie processo contínuo de projeto temporário."],
"adm-estruturas": ["Estrutura funcional agrupa por especialidade; matricial combina dimensões e pode gerar dupla autoridade; estrutura por projetos concentra equipe em entregas específicas.", "Cultura organizacional reúne valores, crenças e práticas compartilhadas.", "Liderança influencia pessoas; estilos variam conforme contexto, equipe e abordagem teórica.", "Estrutura formal e cultura real não são a mesma coisa: organograma mostra relações formais, cultura mostra padrões vividos."],
"adm-planejamento": ["Missão explica razão de existir; visão descreve futuro desejado; valores orientam comportamento.", "SWOT separa fatores internos (forças/fraquezas) e externos (oportunidades/ameaças).", "Objetivo indica resultado desejado; meta tende a torná-lo mensurável e temporal.", "Planejamento estratégico deve desdobrar-se em ações, indicadores e acompanhamento."],
"adm-marketing": ["4 Ps: produto, preço, praça e promoção.", "Segmentação divide mercado/público em grupos com características relevantes para estratégia.", "Marketing não é apenas publicidade; envolve compreender necessidades, proposta de valor e entrega.", "Estratégia de vendas está ligada à conversão e relacionamento, mas deve ser coerente com posicionamento e público-alvo."],
"adm-financeira": ["Orçamento projeta receitas e despesas; fluxo de caixa acompanha entradas e saídas ao longo do tempo.", "Lucro contábil e disponibilidade de caixa não são a mesma coisa.", "Indicadores financeiros ajudam a avaliar liquidez, rentabilidade, endividamento e desempenho conforme finalidade.", "Decisão financeira deve considerar prazo, risco, custo e impacto no caixa."],
"adm-rh": ["Recrutamento atrai candidatos; seleção escolhe; treinamento desenvolve capacidades; avaliação de desempenho compara entrega com critérios.", "Motivação não depende de uma única causa; teorias explicam fatores internos, externos e contextuais.", "Desenvolvimento é mais amplo que treinamento pontual e pode preparar para responsabilidades futuras.", "Liderança e feedback influenciam desempenho, mas precisam de objetivos e critérios claros."],
"adm-empreendedorismo": ["Processo empreendedor envolve identificar oportunidade, avaliar viabilidade, organizar recursos, executar e aprender.", "Plano de negócios estrutura proposta, mercado, operação, equipe, finanças e riscos.", "Inovação pode ocorrer em produto, processo, modelo ou organização; criatividade é geração de ideias, não garantia de implementação.", "Oportunidade difere de ideia: precisa existir problema/necessidade e possibilidade de geração de valor."],
"adm-etica": ["Ética organizacional orienta decisões além do mero cumprimento formal de regras.", "Responsabilidade social considera impactos sobre partes interessadas e sociedade.", "Sustentabilidade integra dimensões ambiental, social e econômica em decisões de longo prazo.", "Conflito de interesses surge quando interesse privado pode interferir na imparcialidade da decisão institucional."],
"pp-conceitos": ["Política pública é ação ou conjunto de decisões governamentais voltadas a problemas públicos.", "Ciclo didático costuma incluir agenda, formulação, decisão, implementação, monitoramento e avaliação; na prática as etapas podem se sobrepor.", "Instrumentos de política são meios usados para produzir comportamento/resultado, como regulação, gasto, informação ou prestação direta.", "Analisar política exige distinguir problema, objetivo, público-alvo, mecanismo de intervenção e resultado esperado."],
"pp-governanca": ["Federalismo distribui autoridade entre entes e exige coordenação em políticas compartilhadas.", "Governança envolve arranjos de decisão, coordenação, responsabilidade e participação entre atores.", "Capacidade estatal inclui recursos, pessoas, informação, coordenação e habilidade de implementar decisões.", "Relação intergovernamental pode envolver cooperação, financiamento, pactuação e conflitos de competência."],
"pp-bases": ["Estatística descritiva resume dados; inferencial busca generalizar conclusões para população a partir de amostras sob pressupostos.", "Média, mediana e dispersão descrevem aspectos diferentes; média isolada pode esconder desigualdade dos dados.", "Microeconomia analisa decisões de agentes e mercados; macroeconomia observa agregados como produção, inflação e emprego.", "Análise de impacto pergunta se a política causou mudança, não apenas se houve mudança ao mesmo tempo."],
"pp-avaliacao": ["Ex ante ocorre antes/na formulação para estimar alternativas e riscos; ex post avalia política já executada.", "Monitoramento acompanha execução e indicadores; avaliação julga mérito, resultados, eficiência ou impacto conforme desenho.", "Gestão de riscos identifica eventos, probabilidade, impacto e respostas possíveis.", "Avaliação de impacto exige comparação contrafactual: o que teria acontecido sem a intervenção."],

# Área de Atuação
"area-atendimento": ["Atendimento de qualidade combina clareza, cortesia, atenção, presteza, eficiência, tolerância, discrição e objetividade.", "Escuta ativa exige compreender demanda antes de responder; interromper ou pressupor pode gerar conflito desnecessário.", "Trabalho em equipe depende de comunicação, divisão de responsabilidades e coordenação.", "Postura profissional inclui respeito, imparcialidade e cuidado com informações recebidas."],
"area-defesa-riscos": ["Risco combina ameaça, vulnerabilidade e impacto potencial; análise de risco busca priorizar medidas de prevenção e resposta.", "Contingência é preparação para cenário adverso; emergência exige resposta coordenada; crise pode envolver impacto amplo e necessidade de gestão especial.", "Informação sensível exige tratamento compatível com grau de proteção e necessidade de conhecimento.", "Defesa pessoal no contexto de prova deve ser estudada como noção preventiva e institucional, não como improvisação de técnicas sem treinamento."],
"area-protecao-escoltas": ["Planejamento de proteção considera missão, pessoas, rota, pontos sensíveis, alternativas e contingências.", "Formação e posição de equipe existem para manter coordenação e proteção do objetivo; mudanças devem seguir comando e contexto.", "Varredura e controle de público buscam identificar riscos antes que se aproximem do protegido/área crítica.", "Condução operacional de veículos deve ser entendida dentro de segurança, planejamento e treinamento institucional, não como direção agressiva."],
"area-seguranca-patrimonial": ["Segurança patrimonial trabalha em camadas: perímetro, acesso, vigilância, monitoramento, proteção de áreas críticas e resposta.", "Controle de acesso identifica quem pode entrar, onde, quando e sob quais condições.", "Barreiras físicas e sistemas eletrônicos se complementam; tecnologia não substitui procedimento e supervisão.", "Plano de segurança deve considerar ativos, ameaças, vulnerabilidades, medidas preventivas e resposta a incidentes."],
"area-incidentes-negociacao": ["Incidente crítico exige comando definido, isolamento, estabilização, comunicação e coordenação de recursos.", "Perímetro controla aproximação e preserva área; cadeia de comando reduz ordens conflitantes.", "Negociação policial básica valoriza escuta ativa, criação de vínculo, redução de tensão e coleta de informações.", "Escalonamento e desescalada devem ser compreendidos como gestão de intensidade da resposta conforme risco e comando institucional."],
"area-incendio": ["Prevenção começa por reduzir fontes de ignição, manter rotas desobstruídas e conhecer meios de alarme e evacuação.", "Classes de incêndio e agente extintor precisam ser compatíveis; usar meio inadequado pode aumentar o risco.", "Rota de fuga, saída de emergência e ponto de encontro fazem parte do abandono organizado.", "NR-23 e normas locais devem ser lidas como referência para proteção contra incêndio dentro do recorte do edital."],
"area-socorrismo": ["Antes do atendimento, verifique segurança do local para não criar nova vítima.", "Acione atendimento especializado e forneça informações claras sobre local, quantidade de vítimas e situação observada.", "APH básico prioriza avaliação inicial, manutenção de funções vitais e prevenção de agravamento até suporte especializado.", "Não realize procedimento para o qual não há treinamento; em prova, priorize segurança, comunicação e sequência básica prevista no conteúdo."],
"area-inteligencia": ["Inteligência produz conhecimento útil à decisão; dado isolado ainda precisa ser avaliado, integrado e analisado.", "Fontes podem variar em origem e confiabilidade; informação deve ser avaliada antes de virar conhecimento.", "Ciclo de produção costuma envolver planejamento, obtenção/coleta, processamento, análise e difusão conforme metodologia institucional.", "Inteligência não é sinônimo de investigação criminal; finalidades e competências podem ser diferentes."],

# Legislação
"leg-maria-penha": ["Lei 11.340/2006 cria mecanismos de prevenção e enfrentamento à violência doméstica e familiar contra a mulher.", "A lei reconhece formas de violência como física, psicológica, sexual, patrimonial e moral.", "Medidas protetivas possuem finalidade preventiva e urgente dentro das hipóteses legais.", "Não reduza a lei apenas a agressão física: contexto doméstico/familiar e outras formas de violência são centrais."],
"leg-drogas": ["Lei 11.343/2006 institui o Sisnad e disciplina prevenção, atenção/reinserção e repressão a condutas relacionadas a drogas.", "Uso/porte para consumo e tráfico possuem regimes e elementos diferentes; quantidade isolada não resolve automaticamente a classificação.", "A análise considera circunstâncias previstas em lei e elementos do caso.", "Estude tipos, sujeitos, procedimentos e causas específicas diretamente na redação vigente."],
"leg-racismo": ["Lei 7.716/1989 trata crimes resultantes de discriminação/preconceito nas hipóteses legais e sofreu alterações relevantes ao longo do tempo.", "Racismo e injúria racial tiveram evolução legislativa e jurisprudencial; use texto vigente para não estudar classificação ultrapassada.", "O bem jurídico envolve igualdade e dignidade, além da proteção contra discriminação.", "Em prova, identifique conduta, motivo discriminatório e tipo legal correspondente."],
"leg-eca": ["ECA adota proteção integral e reconhece criança e adolescente como sujeitos de direitos.", "Criança e adolescente têm faixas etárias definidas legalmente e medidas distintas podem ser aplicáveis conforme situação.", "Direitos fundamentais, medidas de proteção, ato infracional e crimes previstos no Estatuto são blocos diferentes.", "No recorte penal do edital, dê atenção aos crimes e às regras diretamente relacionadas à atuação estatal."],
"leg-ambiental": ["Lei 9.605/1998 disciplina sanções penais e administrativas derivadas de condutas lesivas ao meio ambiente.", "Responsabilização ambiental pode alcançar pessoas físicas e, em hipóteses legais, pessoas jurídicas.", "Crimes são agrupados por bens ambientais protegidos, como fauna, flora, ordenamento urbano/patrimônio cultural e administração ambiental.", "Diferencie infração administrativa de crime ambiental; podem coexistir consequências em esferas distintas."],
"leg-ctb": ["CTB organiza trânsito, competências, regras de circulação, infrações, penalidades, medidas administrativas e crimes de trânsito.", "Infração administrativa e crime de trânsito são categorias diferentes.", "Condutor, veículo, via e autoridade/órgão competente aparecem em relações normativas específicas.", "Para questões operacionais, leia com cuidado deveres de segurança e consequências previstas na redação vigente."],
"leg-desarmamento": ["Lei 10.826/2003 disciplina registro, posse, porte e crimes relacionados a armas de fogo e munições.", "Posse e porte não são sinônimos: local autorizado e circulação fora dele fazem diferença jurídica.", "Arma de uso permitido e restrito seguem classificações/regulamentações específicas.", "Como normas sobre armas sofrem regulamentação e alterações, confira texto legal e atos vigentes antes da prova."],
"leg-abuso": ["Lei 13.869/2019 tipifica abusos cometidos por agentes públicos nas hipóteses legais.", "Os tipos exigem finalidade específica prevista na lei, como prejudicar alguém, beneficiar a si/terceiro ou agir por mero capricho/satisfação pessoal, conforme o dispositivo aplicável.", "Mera divergência na interpretação da lei ou avaliação de fatos/provas não configura abuso por si só.", "Não confunda ilegalidade administrativa com crime de abuso: tipicidade penal exige elementos do tipo."],
"leg-licitacoes": ["Lei 14.133/2021 disciplina licitações e contratos administrativos, princípios, fases, agentes, modalidades, contratação direta, execução e sanções.", "Licitação busca seleção da proposta adequada ao interesse público sob regras de competição e planejamento.", "Dispensa e inexigibilidade são hipóteses diferentes de contratação direta e possuem fundamentos distintos.", "O edital também relaciona crimes licitatórios ao Código Penal; separe infração administrativa de tipo penal."],
"leg-lc1": ["LC municipal 1/1991 disciplina regime jurídico dos servidores de Salvador no recorte indicado pelo edital.", "Estude provimento, direitos, vantagens, deveres, proibições, responsabilidades e regime disciplinar conforme texto consolidado.", "Servidor, cargo, posse, exercício e vacância são conceitos diferentes e devem ser ligados à sequência funcional correta.", "Como é norma municipal alterável, use a versão oficial consolidada como referência final."],
"leg-carreira": ["Lei 9.640/2022 organiza Plano de Carreira e Vencimentos da GCM de Salvador.", "Estrutura de classes/níveis, ingresso, desenvolvimento e remuneração devem ser estudados conforme redação municipal vigente.", "Progressão e promoção podem representar formas diferentes de desenvolvimento funcional; confirme definições da própria lei.", "Relacione a 3ª Classe ao ingresso do concurso apenas conforme o edital e a lei vigente."],
"leg-guardas": ["Lei 13.022/2014 estabelece normas gerais para guardas municipais e define caráter civil da instituição.", "Princípios mínimos incluem proteção de direitos humanos, preservação da vida, patrulhamento preventivo e compromisso com evolução social da comunidade, conforme texto legal.", "Competência geral envolve proteção de bens, serviços, logradouros públicos municipais e instalações do Município.", "Competências específicas devem ser estudadas diretamente no art. correspondente, sem transformar guarda municipal em órgão de competência ilimitada."],
"leg-regimento": ["Decreto 27.731/2016 aprova o Regimento da GCM Salvador conforme o recorte do edital.", "Regimento organiza estrutura interna, unidades, competências e relações funcionais.", "Ao estudar, construa organograma simples com órgão, função e subordinação para evitar confundir atribuições.", "Use o texto oficial municipal porque alterações organizacionais podem modificar nomenclaturas e competências."],
"leg-disciplinar": ["Lei 9.273/2017 disciplina regime disciplinar dos integrantes da GCM Salvador.", "Dever, proibição, infração, sanção e procedimento disciplinar são conceitos relacionados, mas distintos.", "Hierarquia não autoriza cumprimento de ordem manifestamente ilegal; disciplina deve operar dentro da legalidade.", "Estude classificação de infrações e consequências pela redação municipal vigente."],
"leg-organica-poderes": ["Lei Orgânica funciona como norma fundamental do Município dentro da Constituição Federal e Estadual.", "Estude competências do Município, Câmara e Prefeito separadamente.", "Poder Legislativo municipal produz normas e fiscaliza nos termos da Lei Orgânica; Executivo administra e executa políticas dentro de suas atribuições.", "Não confunda competência do Município com competência de um órgão específico da administração."],
"leg-organica-adm": ["Administração, servidores, bens e serviços públicos possuem regras orgânicas próprias no Município.", "Planejamento, orçamento e finanças ligam prioridades políticas à previsão e execução de receitas/despesas.", "Políticas sociais e desenvolvimento urbano aparecem como campos de atuação municipal e devem ser relacionados às competências locais.", "Leia a Lei Orgânica por blocos e produza mapa de quem faz o quê."],
"leg-organizacao-adm": ["Administração direta é composta por órgãos da própria pessoa política; administração indireta por entidades com personalidade jurídica própria criadas/autorizadas por lei conforme espécie.", "Órgão não possui personalidade jurídica própria; entidade da administração indireta possui.", "Competência define atribuição jurídica do agente/órgão e não pode ser presumida apenas pela conveniência.", "Responsabilidade do agente público deve ser analisada conforme função, dever e regime jurídico aplicável."],
"leg-tributario": ["Lei 7.186/2006 é o Código Tributário e de Rendas de Salvador no recorte do edital.", "Tributos municipais, obrigações tributárias, administração e fiscalização são os eixos centrais cobrados.", "Obrigação principal e acessória têm objetos diferentes; descumprimento de obrigação acessória pode gerar penalidade conforme lei.", "Evite estudar tributos federais/estaduais que não pertencem ao recorte municipal apenas por associação com Direito Tributário."],
"leg-etica-transparencia": ["Ética e integridade orientam prevenção de conflitos de interesse, desvios e uso indevido de recursos públicos.", "Transparência e acesso à informação convivem com hipóteses legais de sigilo e proteção de dados; publicidade não significa exposição irrestrita.", "Controle da Administração pode ser interno, externo e social conforme mecanismos jurídicos.", "Prestação e fiscalização de serviços públicos devem observar legalidade, finalidade e direitos do usuário."],
"leg-direitos-cidadaos": ["Cidadão possui direitos perante a Administração, incluindo tratamento adequado, acesso a serviços e informações nos limites legais.", "Também existem deveres de colaboração, identificação e respeito às regras do procedimento quando exigidos.", "Agente público deve atuar dentro de competência e finalidade pública, sem favorecer interesse particular.", "Em atendimento, legalidade e impessoalidade precisam coexistir com clareza, respeito e eficiência."],
}

syllabus = json.loads(SYLLABUS_PATH.read_text(encoding="utf-8"))
lessons = json.loads(LESSONS_PATH.read_text(encoding="utf-8"))
all_topic_ids = {
    topic["id"]
    for subject in syllabus["subjects"]
    for topic in subject["topics"]
}
missing = sorted(all_topic_ids - set(K))
extra = sorted(set(K) - all_topic_ids)
if missing or extra:
    raise SystemExit(f"Mapa de aprofundamento inválido. Faltando={missing}; extras={extra}")

for lesson in lessons:
    topic_id = lesson["topicId"]
    section = {
        "title": "Aprofundamento específico do tópico",
        "items": K[topic_id],
    }
    sections = [s for s in lesson.get("sections", []) if s.get("title") != section["title"]]
    # Insere logo após fundamentos, antes do método de resolução.
    insert_at = 3 if len(sections) >= 3 else len(sections)
    sections.insert(insert_at, section)
    lesson["sections"] = sections
    lesson["theoryMinutes"] = int(lesson.get("theoryMinutes", 45)) + 15
    lesson["estimatedMinutes"] = int(lesson.get("estimatedMinutes", 70)) + 15
    lesson["depth"] = "concurso-aprofundado-v4"

LESSONS_PATH.write_text(json.dumps(lessons, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Aprofundamento específico aplicado a {len(lessons)} aulas.")
